### ISSUE TITLE
tests duplication

### ISSUE THREAD

**Issue by alexxa** [RedHatQE/rhui3-automation#137]
Instead of tests/code duplication between rhui3-automation/tests/rhui3_tests/test_*.py, they should be imported or maybe inherited e.g.

**Comment by RadekBiba** [comment]
Could you please be more specific?

Perhaps you meant this: There are test cases that cover a specific area, e.g. CDS management, where only CDS is dealt with. And then there are test cases that involve a test repository and a client machine, and possibly a specific functionality (GPG, updateinfo, ...), in which case it's necessary to add a CDS in the beginning so that the test is self-sufficient and the client can consume the repo. Such a client test case will fail if the CDS cannot be added for any reason, but actual CDS management isn't the focus of it, the addition is kind of like a part of the setup. I can't think of a way to import/inherit the "addition test" from test_cds.py. We have libraries that we import so that the individual test cases don't have to duplicate the exact low-level steps.

I would stress the word self-suficient as that's the point. Each test case is, IMHO, responsible for its setup (and cleanup) so it can be executed independently. For example in the case of RHEL 8 client testing, you can now choose to run only a test case that involves a client and ignore the rest. Some setup is necessary, and I totally agree that the setup will be duplicate in all client-focused test cases. One thing I've thought about before is the ability to set up the environment and leave it running, and support for "skip the setup" in the tests themselves, which would save some time if I knew I was going to need the same environment multiple times. I might implement this sometime this year.

However, please elaborate on what you mean by duplication here.

**Comment by alexxa** [comment]
for example this one was used 4 times: https://github.com/RedHatQE/rhui3-automation/pull/136/files#diff-07d7aa7e4019bcae62e9cf4e731f14cbR207

if any change in that TC, one needs to correct it 4 times :/

**Comment by RadekBiba** [comment]
Ah, that one. Thanks. That scenario is indeed tested in four places, CDS & HA management in the interactive mode & in the CLI. I did consider making a method for it but then I decided to put everything to the test cases themselves. AFAICT there's currently no good place for such a method, but I'll think about it again and likely create a special library first.
