### ISSUE TITLE
dnf support

### ISSUE THREAD

**Issue by Skullman** [RedHatQE/rhui3-automation#5]
For future, when yum will be obsoleted we might need a possibility to use dnf on those machines. Please note that we will still need yum for installation on RHEL6 machines.

**Comment by alexxa** [comment]
Fix by package module [1] when ansible 2.0 is released. 

[1] http://docs.ansible.com/ansible/package_module.html

**Comment by alexxa** [comment]
Blocked by https://github.com/RedHatQE/rhui3-automation/issues/11#issuecomment-223956988

**Comment by RadekBiba** [comment]
I took a look at this while making changes for RHEL 8. Here's the current status:

- The deployment part of rhui3-automation uses the `yum` Ansible module to check if the `rhui-local` repo, created by `setup_package_repos` from the ISO, is all right. It's safe to keep this (python-2-only) module because it's highly unlikely that RHUI 3 will become installable on (python-3 based) RHEL 8. Other than that, the (manager-agnostic) `package` module is used to install stuff. Of course, if we ever need to do something specific on RHEL 8+ that the `package` module can't do, we can use the `dnf` module conditionally.
- The test cases and libraries run raw `yum` commands on the CLI, RHUA, and CDS nodes (with one exception where `dnf -v` is used if RHEL 8 is detected, and another one where the `dnf` cache directory is flushed on RHEL 8). This is okay as `(/usr/bin/)yum` is available across all RHEL versions for compatibility reasons; it's not obsolete in RHEL 8.

No action is required to resolve this issue.

**Comment by RadekBiba** [comment]
Closing based on the comment above.
